# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeCRsCpp <- function(x, exp, lambda) {
    .Call('algstat_computeCRsCpp', PACKAGE = 'algstat', x, exp, lambda)
}

computeG2sCpp <- function(x, exp) {
    .Call('algstat_computeG2sCpp', PACKAGE = 'algstat', x, exp)
}

computeNMsCpp <- function(x, exp) {
    .Call('algstat_computeNMsCpp', PACKAGE = 'algstat', x, exp)
}

computeUProbsCpp <- function(x) {
    .Call('algstat_computeUProbsCpp', PACKAGE = 'algstat', x)
}

computeX2sCpp <- function(x, exp) {
    .Call('algstat_computeX2sCpp', PACKAGE = 'algstat', x, exp)
}

constr <- function(A, suffstat) {
    .Call('algstat_constr', PACKAGE = 'algstat', A, suffstat)
}

HitnRun <- function(current, move) {
    .Call('algstat_HitnRun', PACKAGE = 'algstat', current, move)
}

metropolis_hypergeometric_cpp <- function(current, moves, iter, thin, hit_and_run) {
    .Call('algstat_metropolis_hypergeometric_cpp', PACKAGE = 'algstat', current, moves, iter, thin, hit_and_run)
}

metropolis_uniform_cpp <- function(current, moves, iter, thin, hit_and_run) {
    .Call('algstat_metropolis_uniform_cpp', PACKAGE = 'algstat', current, moves, iter, thin, hit_and_run)
}

rfiberOne <- function(A, b) {
    .Call('algstat_rfiberOne', PACKAGE = 'algstat', A, b)
}

timesTwo <- function(constr, objfun, minimize, solver) {
    .Call('algstat_timesTwo', PACKAGE = 'algstat', constr, objfun, minimize, solver)
}

walk <- function(current, moves, iter, thin) {
    .Call('algstat_walk', PACKAGE = 'algstat', current, moves, iter, thin)
}

